name: mimosaBlog

on: push

jobs:
  build:
    name: build-blog
    runs-on: ubuntu-latest
    steps:
      - name: use node.js 16.x
        uses: action/setup-node@v2
        with:
          node-version: "16",
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependences
        run: npm install
      - name:  build
        run: npm run docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

